# NumPy

In [18]:
a = [1,2,3,4]
b = [2,3,4,5]

In [19]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

## NumPy Array'i Oluşturmak

In [23]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [24]:
a = np.array([1,2,3,4])

In [25]:
type(a)

numpy.ndarray

In [26]:
np.array([3.2,2,3,4,5])

array([3.2, 2. , 3. , 4. , 5. ])

In [27]:
np.array([3.2,2,3,4,5],dtype='int')

array([3, 2, 3, 4, 5])

## Sıfırdan Array Oluşturmak

In [28]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [32]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [37]:
np.random.normal(0,1,(3,3))

array([[-1.26968474,  0.97396211,  0.72532518],
       [-0.87983127, -0.17459636,  1.18926769],
       [-0.17614598, -1.15801213,  1.35567964]])

In [38]:
np.random.randint(0,10,(3,3))

array([[7, 6, 4],
       [4, 6, 6],
       [7, 2, 6]])

## NumPy Array Özellikleri

* **ndim**: boyut sayisi
* **shape**: boyut bilgisi
* **size**: toplam eleman sayisi
* **dtype**: array veri tipi 

In [67]:
np.random.randint(10,size = 10)

array([1, 9, 1, 2, 9, 9, 5, 2, 9, 6])

In [40]:
a = np.random.randint(10,size = 10)

In [41]:
a.ndim

1

In [42]:
a.shape

(10,)

In [43]:
a.size

10

In [44]:
a.dtype

dtype('int64')

In [45]:
b = np.random.randint(10,size = (3,5))

In [46]:
b

array([[6, 9, 4, 3, 7],
       [1, 0, 5, 2, 6],
       [3, 2, 8, 1, 3]])

In [47]:
b.ndim

2

In [48]:
b.shape

(3, 5)

In [49]:
b.size

15

In [61]:
b.dtype

dtype('int64')

## Yeniden Şekillendirme (reshaping)

In [70]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
a = np.arange(1,10)

In [86]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a.ndim

1

In [ ]:
b = a.reshape((1,9))

In [88]:
b.ndim

2

## Array Birleştirme (Concatenation)

In [89]:
x = np.array([1,2,3])
y = np.array([4,5,6])

array([1, 2, 3, 4, 5, 6])

In [90]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [92]:
z = np.array([7,8,9])

In [93]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### iki boyut

In [95]:
a = np.array([[1,2,3],
              [4,5,6]])

In [96]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [97]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [98]:
x = np.array([1,2,3,99,99,3,2,1])

In [101]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [104]:
x,y,z = np.split(x,[3,5])

In [107]:
x

array([1, 2, 3])

In [108]:
y

array([99, 99])

In [109]:
z

array([3, 2, 1])

### iki boyutlu ayırma

In [110]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [116]:
alt,ust = np.vsplit(m,[2])

In [113]:
alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [117]:
ust

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Sıralam (Sorting)

In [120]:
v = np.array([2,5,3,77,2,786,3,1,99])

In [121]:
v

array([  2,   5,   3,  77,   2, 786,   3,   1,  99])

In [122]:
np.sort(v)

array([  1,   2,   2,   3,   3,   5,  77,  99, 786])

In [123]:
v

array([  2,   5,   3,  77,   2, 786,   3,   1,  99])

### diziyi degiştirmiyor np.sort
## iki boyutlu siralama

In [179]:
m = np.random.normal(20,5, (3,3))
m

array([[10.9161438 , 26.76429468, 14.81437362],
       [25.72648812, 20.86467147, 21.86218346],
       [25.39946939, 14.03186807, 14.44504206]])

In [181]:
np.sort(m,axis=0)

array([[10.9161438 , 14.03186807, 14.44504206],
       [25.39946939, 20.86467147, 14.81437362],
       [25.72648812, 26.76429468, 21.86218346]])

In [182]:
np.sort(m,axis=1)

array([[10.9161438 , 14.81437362, 26.76429468],
       [20.86467147, 21.86218346, 25.72648812],
       [14.03186807, 14.44504206, 25.39946939]])

In [183]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [185]:
my_arr = np.arange(1_000_000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

## Index ile Elemanlara Erişmek

In [186]:
a = np.random.randint(10,size = 10)  
a

array([3, 0, 2, 9, 0, 1, 2, 3, 2, 3])

In [187]:
a[0]

3

In [188]:
a[-1]

3

In [189]:
a[0] = 100
a

array([100,   0,   2,   9,   0,   1,   2,   3,   2,   3])

In [190]:
m = np.random.randint(10,size = (3,5))
m

array([[2, 2, 8, 5, 7],
       [3, 0, 8, 1, 7],
       [9, 3, 5, 7, 0]])

In [191]:
m[2,2]

5

## Slicing ile Elemanlara Erişmek (Alt kümelere erişmek)

In [192]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [193]:
a[0:3]

array([20, 21, 22])

In [194]:
a[:3]

array([20, 21, 22])

In [195]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [197]:
a[0::2]

array([20, 22, 24, 26, 28])

### iki boyutlu alt küme işlemleri

In [198]:
m = np.random.randint(10,size = (5,5))
m

array([[7, 9, 0, 4, 4],
       [7, 5, 4, 7, 6],
       [5, 6, 7, 6, 9],
       [3, 3, 1, 6, 5],
       [4, 5, 3, 1, 6]])

In [199]:
m[:,0]

array([7, 7, 5, 3, 4])

In [200]:
m[:,1]

array([9, 5, 6, 3, 5])

In [201]:
m

array([[7, 9, 0, 4, 4],
       [7, 5, 4, 7, 6],
       [5, 6, 7, 6, 9],
       [3, 3, 1, 6, 5],
       [4, 5, 3, 1, 6]])

In [202]:
m[0,:]

array([7, 9, 0, 4, 4])

In [206]:
m[1:4,3:4]

array([[7],
       [6],
       [6]])

In [207]:
m[:,0:2]

array([[7, 9],
       [7, 5],
       [5, 6],
       [3, 3],
       [4, 5]])

In [208]:
a = np.random.randint(10,size = (5,5))
a

array([[3, 0, 6, 1, 5],
       [2, 0, 9, 0, 2],
       [6, 7, 3, 3, 3],
       [1, 4, 1, 6, 2],
       [2, 1, 2, 2, 1]])

In [209]:
alt_a = a[0:3,0:2]
alt_a

array([[3, 0],
       [2, 0],
       [6, 7]])

In [210]:
alt_a[0,0] = 9999
a

array([[9999,    0,    6,    1,    5],
       [   2,    0,    9,    0,    2],
       [   6,    7,    3,    3,    3],
       [   1,    4,    1,    6,    2],
       [   2,    1,    2,    2,    1]])

In [211]:
m = np.random.randint(10,size = (5,5))
m

array([[2, 5, 6, 6, 3],
       [1, 2, 8, 8, 6],
       [7, 4, 5, 1, 2],
       [9, 5, 8, 3, 4],
       [6, 6, 6, 7, 7]])

In [212]:
alt_b = m[0:3,0:2].copy()

In [214]:
alt_b[0,0] = 9999
alt_b

array([[9999,    5],
       [   1,    2],
       [   7,    4]])

In [215]:
m

array([[2, 5, 6, 6, 3],
       [1, 2, 8, 8, 6],
       [7, 4, 5, 1, 2],
       [9, 5, 8, 3, 4],
       [6, 6, 6, 7, 7]])

## Fancy Index ile Elemanlara Erişmek

In [216]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [217]:
v[1]

3

In [218]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [219]:
alt_index = [1,3,5]

In [220]:
v[alt_index]

array([ 3,  9, 15])

### iki boyutta fancy

In [221]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [229]:
satir = np.array([0,2])
sutun = np.array([0,2])

In [232]:
m[satir,sutun]

array([0, 8])

In [237]:
m[0:2,0:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [238]:
m[0,[1,2]]

array([1, 2])

In [239]:
m[:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

## Koşullu Eleman İşlemleri

In [241]:
v = np.array([1,2,3,4,5])

In [242]:
v>5

array([False, False, False, False, False])

In [244]:
v[v >2]

array([3, 4, 5])

In [245]:
v[v>=3]

array([3, 4, 5])

In [246]:
v[v==3]

array([3])

In [247]:
v[v!=3]

array([1, 2, 4, 5])

## Matematiksel İşlemler

In [248]:
v = np.array([1,2,3,4,5])

In [249]:
np?

Type:        module
String form: <module 'numpy' from '/opt/homebrew/lib/python3.10/site-packages/numpy/__init__.py'>
File:        /opt/homebrew/lib/python3.10/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x 

## Denklem Çözme
2*x0+x1 = 22
x0+5*x1 = 40
x0,x1 ?

In [251]:
katsayilar = np.array([[2,1],[1,5]])
sonuclar = np.array([22,40])

In [252]:
x0,x1 = np.linalg.solve(katsayilar,sonuclar)
x0,x1

(7.777777777777778, 6.444444444444445)