# NumPy

In [18]:
a = [1,2,3,4]
b = [2,3,4,5]

In [19]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

## NumPy Array'i Oluşturmak

In [22]:
import numpy as np

In [23]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [24]:
a = np.array([1,2,3,4])

In [25]:
type(a)

numpy.ndarray

In [26]:
np.array([3.2,2,3,4,5])

array([3.2, 2. , 3. , 4. , 5. ])

In [27]:
np.array([3.2,2,3,4,5],dtype='int')

array([3, 2, 3, 4, 5])

## Sıfırdan Array Oluşturmak

In [28]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [32]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [37]:
np.random.normal(0,1,(3,3))

array([[-1.26968474,  0.97396211,  0.72532518],
       [-0.87983127, -0.17459636,  1.18926769],
       [-0.17614598, -1.15801213,  1.35567964]])

In [38]:
np.random.randint(0,10,(3,3))

array([[7, 6, 4],
       [4, 6, 6],
       [7, 2, 6]])

## NumPy Array Özellikleri

* **ndim**: boyut sayisi
* **shape**: boyut bilgisi
* **size**: toplam eleman sayisi
* **dtype**: array veri tipi 

In [ ]:
import numpy as np

In [39]:
np.random.randint(10,size = 10)

array([0, 4, 5, 3, 2, 7, 9, 0, 7, 7])

In [40]:
a = np.random.randint(10,size = 10)

In [41]:
a.ndim

1

In [42]:
a.shape

(10,)

In [43]:
a.size

10

In [44]:
a.dtype

dtype('int64')

In [45]:
b = np.random.randint(10,size = (3,5))

In [46]:
b

array([[6, 9, 4, 3, 7],
       [1, 0, 5, 2, 6],
       [3, 2, 8, 1, 3]])

In [47]:
b.ndim

2

In [48]:
b.shape

(3, 5)

In [49]:
b.size

15

In [50]:
b.dtype

dtype('int64')