# NumPy

In [18]:
a = [1,2,3,4]
b = [2,3,4,5]

In [19]:
ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

## NumPy Array'i Oluşturmak

In [23]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [24]:
a = np.array([1,2,3,4])

In [25]:
type(a)

numpy.ndarray

In [26]:
np.array([3.2,2,3,4,5])

array([3.2, 2. , 3. , 4. , 5. ])

In [27]:
np.array([3.2,2,3,4,5],dtype='int')

array([3, 2, 3, 4, 5])

## Sıfırdan Array Oluşturmak

In [28]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones((3,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [32]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [36]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [37]:
np.random.normal(0,1,(3,3))

array([[-1.26968474,  0.97396211,  0.72532518],
       [-0.87983127, -0.17459636,  1.18926769],
       [-0.17614598, -1.15801213,  1.35567964]])

In [38]:
np.random.randint(0,10,(3,3))

array([[7, 6, 4],
       [4, 6, 6],
       [7, 2, 6]])

## NumPy Array Özellikleri

* **ndim**: boyut sayisi
* **shape**: boyut bilgisi
* **size**: toplam eleman sayisi
* **dtype**: array veri tipi 

In [67]:
np.random.randint(10,size = 10)

array([1, 9, 1, 2, 9, 9, 5, 2, 9, 6])

In [40]:
a = np.random.randint(10,size = 10)

In [41]:
a.ndim

1

In [42]:
a.shape

(10,)

In [43]:
a.size

10

In [44]:
a.dtype

dtype('int64')

In [45]:
b = np.random.randint(10,size = (3,5))

In [46]:
b

array([[6, 9, 4, 3, 7],
       [1, 0, 5, 2, 6],
       [3, 2, 8, 1, 3]])

In [47]:
b.ndim

2

In [48]:
b.shape

(3, 5)

In [49]:
b.size

15

In [61]:
b.dtype

dtype('int64')

## Yeniden Şekillendirme (reshaping)

In [70]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
a = np.arange(1,10)

In [86]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a.ndim

1

In [ ]:
b = a.reshape((1,9))

In [88]:
b.ndim

2

## Array Birleştirme (Concatenation)

In [89]:
x = np.array([1,2,3])
y = np.array([4,5,6])

array([1, 2, 3, 4, 5, 6])

In [90]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [92]:
z = np.array([7,8,9])

In [93]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### iki boyut

In [95]:
a = np.array([[1,2,3],
              [4,5,6]])

In [96]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [97]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [98]:
x = np.array([1,2,3,99,99,3,2,1])

In [101]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [104]:
x,y,z = np.split(x,[3,5])

In [107]:
x

array([1, 2, 3])

In [108]:
y

array([99, 99])

In [109]:
z

array([3, 2, 1])

### iki boyutlu ayırma

In [110]:
m = np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [116]:
alt,ust = np.vsplit(m,[2])

In [113]:
alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [117]:
ust

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Sıralam (Sorting)

In [120]:
v = np.array([2,5,3,77,2,786,3,1,99])

In [121]:
v

array([  2,   5,   3,  77,   2, 786,   3,   1,  99])

In [122]:
np.sort(v)

array([  1,   2,   2,   3,   3,   5,  77,  99, 786])

In [123]:
v

array([  2,   5,   3,  77,   2, 786,   3,   1,  99])

### diziyi degiştirmiyor np.sort
## iki boyutlu siralama

In [179]:
m = np.random.normal(20,5, (3,3))
m

array([[10.9161438 , 26.76429468, 14.81437362],
       [25.72648812, 20.86467147, 21.86218346],
       [25.39946939, 14.03186807, 14.44504206]])

In [181]:
np.sort(m,axis=0)

array([[10.9161438 , 14.03186807, 14.44504206],
       [25.39946939, 20.86467147, 14.81437362],
       [25.72648812, 26.76429468, 21.86218346]])

In [182]:
np.sort(m,axis=1)

array([[10.9161438 , 14.81437362, 26.76429468],
       [20.86467147, 21.86218346, 25.72648812],
       [14.03186807, 14.44504206, 25.39946939]])

In [183]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [185]:
my_arr = np.arange(1_000_000)
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

## Index ile Elemanlara Erişmek

In [186]:
a = np.random.randint(10,size = 10)  
a

array([3, 0, 2, 9, 0, 1, 2, 3, 2, 3])

In [187]:
a[0]

3

In [188]:
a[-1]

3

In [189]:
a[0] = 100
a

array([100,   0,   2,   9,   0,   1,   2,   3,   2,   3])

In [190]:
m = np.random.randint(10,size = (3,5))
m

array([[2, 2, 8, 5, 7],
       [3, 0, 8, 1, 7],
       [9, 3, 5, 7, 0]])

In [191]:
m[2,2]

5